### ISSUE TITLE
NP Likeness model datafile missing 

### ISSUE THREAD

**Issue by JamesJeffryes** [JamesJeffryes/MINE-Database#5]
From @jonstrutz11 :

So I am trying to run pickaxe but store in a mongodb rather than export a tsv file. I ended up getting it to work, but this was the error report:

Here is a copy of the error report:
Generation 1: 25 percent complete
Generation 1: 50 percent complete
Generation 1: 75 percent complete
Generation 1: 100 percent complete
Generation 1 produced 130 new compounds and 131 new reactions in 0.8364100456237793 sec
Saving results to Lignin_c4_g1
reading NP model ...

Traceback (most recent call last):
  File "pickaxe.py", line 773, in <module>
    pk.save_to_MINE(options.database)
  File "pickaxe.py", line 651, in save_to_MINE
    comp_dict, bulk=bulk_c)
  File "C:\Users\Jon\Anaconda3\lib\site-packages\minedatabase-0.1-py3.5.egg\minedatabase\databases.py", line 309, in insert_compound
    self.np_model = np.readNPModel()
  File "C:\Users\Jon\Anaconda3\lib\site-packages\minedatabase-0.1-py3.5.egg\minedatabase\NP_Score\npscorer.py", line 24, in readNPModel
    fscore = pickle.load(gzip.open(filename))
  File "C:\Users\Jon\Anaconda3\lib\gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "C:\Users\Jon\Anaconda3\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jon\\Anaconda3\\lib\\site-packages\\minedatabase-0.1-py3.5.egg\\minedatabase\\NP_Score\\publicnp.model.gz'

I looked for the file manually and I have the NP_Score folder at the right location but the publicnp.model.gz file does not exist there. I noticed that the file exists in the NP_Score folder in the project folder though so I just copied it manually into the anaconda library. Seems to work now.

Just wanted to give you a heads up in case this may indicate some sort of bug you may have missed.

**Comment by JamesJeffryes** [comment]
fixed by PR #8
